-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity store is
generic (
    C_M_AXI_DATA_PORT_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_DATA_PORT_ID_WIDTH : INTEGER := 1;
    C_M_AXI_DATA_PORT_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_DATA_PORT_DATA_WIDTH : INTEGER := 128;
    C_M_AXI_DATA_PORT_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_DATA_PORT_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_DATA_PORT_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_DATA_PORT_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_BUS_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_BUS_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_DATA_PORT_USER_VALUE : INTEGER := 0;
    C_M_AXI_DATA_PORT_PROT_VALUE : INTEGER := 0;
    C_M_AXI_DATA_PORT_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_data_port_AWVALID : OUT STD_LOGIC;
    m_axi_data_port_AWREADY : IN STD_LOGIC;
    m_axi_data_port_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_ADDR_WIDTH-1 downto 0);
    m_axi_data_port_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_ID_WIDTH-1 downto 0);
    m_axi_data_port_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_data_port_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_port_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_port_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_port_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_port_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_port_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_port_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_port_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_AWUSER_WIDTH-1 downto 0);
    m_axi_data_port_WVALID : OUT STD_LOGIC;
    m_axi_data_port_WREADY : IN STD_LOGIC;
    m_axi_data_port_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_DATA_WIDTH-1 downto 0);
    m_axi_data_port_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_DATA_WIDTH/8-1 downto 0);
    m_axi_data_port_WLAST : OUT STD_LOGIC;
    m_axi_data_port_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_ID_WIDTH-1 downto 0);
    m_axi_data_port_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_WUSER_WIDTH-1 downto 0);
    m_axi_data_port_ARVALID : OUT STD_LOGIC;
    m_axi_data_port_ARREADY : IN STD_LOGIC;
    m_axi_data_port_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_ADDR_WIDTH-1 downto 0);
    m_axi_data_port_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_ID_WIDTH-1 downto 0);
    m_axi_data_port_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_data_port_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_port_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_port_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_port_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_port_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_port_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_port_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_port_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_ARUSER_WIDTH-1 downto 0);
    m_axi_data_port_RVALID : IN STD_LOGIC;
    m_axi_data_port_RREADY : OUT STD_LOGIC;
    m_axi_data_port_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_DATA_WIDTH-1 downto 0);
    m_axi_data_port_RLAST : IN STD_LOGIC;
    m_axi_data_port_RID : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_ID_WIDTH-1 downto 0);
    m_axi_data_port_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_RUSER_WIDTH-1 downto 0);
    m_axi_data_port_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_port_BVALID : IN STD_LOGIC;
    m_axi_data_port_BREADY : OUT STD_LOGIC;
    m_axi_data_port_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_port_BID : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_ID_WIDTH-1 downto 0);
    m_axi_data_port_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_PORT_BUSER_WIDTH-1 downto 0);
    store_queue_V_V_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    store_queue_V_V_TVALID : IN STD_LOGIC;
    store_queue_V_V_TREADY : OUT STD_LOGIC;
    g2s_dep_queue_V_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    g2s_dep_queue_V_TVALID : IN STD_LOGIC;
    g2s_dep_queue_V_TREADY : OUT STD_LOGIC;
    s2g_dep_queue_V_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    s2g_dep_queue_V_TVALID : OUT STD_LOGIC;
    s2g_dep_queue_V_TREADY : IN STD_LOGIC;
    out_mem_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_mem_V_EN_A : OUT STD_LOGIC;
    out_mem_V_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_mem_V_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
    out_mem_V_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
    out_mem_V_Clk_A : OUT STD_LOGIC;
    out_mem_V_Rst_A : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CONTROL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CONTROL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CONTROL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CONTROL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of store is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "store,hls_ip_2020_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=2.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.750000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=1241,HLS_SYN_LUT=1259,HLS_VERSION=2020_1_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal outputs_V : STD_LOGIC_VECTOR (31 downto 0);
    signal data_port_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal data_port_blk_n_W : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln552_reg_464 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln552_reg_464_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal data_port_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal store_queue_V_V_TDATA_blk_n : STD_LOGIC;
    signal g2s_dep_queue_V_TDATA_blk_n : STD_LOGIC;
    signal tmp_6_fu_280_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal s2g_dep_queue_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln547_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_336_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal tmp_7_reg_449 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_port_AWVALID : STD_LOGIC;
    signal data_port_AWREADY : STD_LOGIC;
    signal data_port_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal data_port_WVALID : STD_LOGIC;
    signal data_port_WREADY : STD_LOGIC;
    signal data_port_ARREADY : STD_LOGIC;
    signal data_port_RVALID : STD_LOGIC;
    signal data_port_RDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal data_port_RLAST : STD_LOGIC;
    signal data_port_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal data_port_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal data_port_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal data_port_BVALID : STD_LOGIC;
    signal data_port_BREADY : STD_LOGIC;
    signal data_port_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal data_port_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal data_port_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln552_reg_225 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_cast_fu_246_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast_reg_392 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal tmp_V_reg_397 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_reg_402 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_260_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_reg_407 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln304_fu_308_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln304_reg_426 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln552_fu_312_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln552_reg_431 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_fu_321_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_reg_439 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_predicate_op53_write_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal add_ln551_fu_331_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln551_reg_444 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln552_fu_353_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln552_reg_459 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln552_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state4_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln552_fu_362_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal out_mem_V_load_reg_478 : STD_LOGIC_VECTOR (127 downto 0);
    signal sram_idx_V_1_fu_382_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sram_idx_V_1_reg_483 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal add_ln304_fu_387_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln304_reg_488 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state4 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal sram_idx_V_0_reg_194 : STD_LOGIC_VECTOR (15 downto 0);
    signal dram_idx_V_reg_204 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_0_reg_214 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln552_1_fu_377_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln551_fu_343_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal out_mem_V_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_236_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_3_fu_270_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln215_fu_327_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln552_1_fu_368_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln552_1_fu_372_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal regslice_both_s2g_dep_queue_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state12_io : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_store_queue_V_V_U_apdone_blk : STD_LOGIC;
    signal store_queue_V_V_TDATA_int : STD_LOGIC_VECTOR (127 downto 0);
    signal store_queue_V_V_TVALID_int : STD_LOGIC;
    signal store_queue_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_store_queue_V_V_U_ack_in : STD_LOGIC;
    signal regslice_both_g2s_dep_queue_V_U_apdone_blk : STD_LOGIC;
    signal g2s_dep_queue_V_TDATA_int : STD_LOGIC_VECTOR (7 downto 0);
    signal g2s_dep_queue_V_TVALID_int : STD_LOGIC;
    signal g2s_dep_queue_V_TREADY_int : STD_LOGIC;
    signal regslice_both_g2s_dep_queue_V_U_ack_in : STD_LOGIC;
    signal s2g_dep_queue_V_TVALID_int : STD_LOGIC;
    signal s2g_dep_queue_V_TREADY_int : STD_LOGIC;
    signal regslice_both_s2g_dep_queue_V_U_vld_out : STD_LOGIC;

    component store_CONTROL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        outputs_V : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component store_data_port_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    store_CONTROL_BUS_s_axi_U : component store_CONTROL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CONTROL_BUS_AWVALID,
        AWREADY => s_axi_CONTROL_BUS_AWREADY,
        AWADDR => s_axi_CONTROL_BUS_AWADDR,
        WVALID => s_axi_CONTROL_BUS_WVALID,
        WREADY => s_axi_CONTROL_BUS_WREADY,
        WDATA => s_axi_CONTROL_BUS_WDATA,
        WSTRB => s_axi_CONTROL_BUS_WSTRB,
        ARVALID => s_axi_CONTROL_BUS_ARVALID,
        ARREADY => s_axi_CONTROL_BUS_ARREADY,
        ARADDR => s_axi_CONTROL_BUS_ARADDR,
        RVALID => s_axi_CONTROL_BUS_RVALID,
        RREADY => s_axi_CONTROL_BUS_RREADY,
        RDATA => s_axi_CONTROL_BUS_RDATA,
        RRESP => s_axi_CONTROL_BUS_RRESP,
        BVALID => s_axi_CONTROL_BUS_BVALID,
        BREADY => s_axi_CONTROL_BUS_BREADY,
        BRESP => s_axi_CONTROL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        outputs_V => outputs_V);

    store_data_port_m_axi_U : component store_data_port_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 128,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_DATA_PORT_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_DATA_PORT_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_DATA_PORT_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_DATA_PORT_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_DATA_PORT_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_DATA_PORT_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_DATA_PORT_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_DATA_PORT_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_DATA_PORT_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_DATA_PORT_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_DATA_PORT_CACHE_VALUE)
    port map (
        AWVALID => m_axi_data_port_AWVALID,
        AWREADY => m_axi_data_port_AWREADY,
        AWADDR => m_axi_data_port_AWADDR,
        AWID => m_axi_data_port_AWID,
        AWLEN => m_axi_data_port_AWLEN,
        AWSIZE => m_axi_data_port_AWSIZE,
        AWBURST => m_axi_data_port_AWBURST,
        AWLOCK => m_axi_data_port_AWLOCK,
        AWCACHE => m_axi_data_port_AWCACHE,
        AWPROT => m_axi_data_port_AWPROT,
        AWQOS => m_axi_data_port_AWQOS,
        AWREGION => m_axi_data_port_AWREGION,
        AWUSER => m_axi_data_port_AWUSER,
        WVALID => m_axi_data_port_WVALID,
        WREADY => m_axi_data_port_WREADY,
        WDATA => m_axi_data_port_WDATA,
        WSTRB => m_axi_data_port_WSTRB,
        WLAST => m_axi_data_port_WLAST,
        WID => m_axi_data_port_WID,
        WUSER => m_axi_data_port_WUSER,
        ARVALID => m_axi_data_port_ARVALID,
        ARREADY => m_axi_data_port_ARREADY,
        ARADDR => m_axi_data_port_ARADDR,
        ARID => m_axi_data_port_ARID,
        ARLEN => m_axi_data_port_ARLEN,
        ARSIZE => m_axi_data_port_ARSIZE,
        ARBURST => m_axi_data_port_ARBURST,
        ARLOCK => m_axi_data_port_ARLOCK,
        ARCACHE => m_axi_data_port_ARCACHE,
        ARPROT => m_axi_data_port_ARPROT,
        ARQOS => m_axi_data_port_ARQOS,
        ARREGION => m_axi_data_port_ARREGION,
        ARUSER => m_axi_data_port_ARUSER,
        RVALID => m_axi_data_port_RVALID,
        RREADY => m_axi_data_port_RREADY,
        RDATA => m_axi_data_port_RDATA,
        RLAST => m_axi_data_port_RLAST,
        RID => m_axi_data_port_RID,
        RUSER => m_axi_data_port_RUSER,
        RRESP => m_axi_data_port_RRESP,
        BVALID => m_axi_data_port_BVALID,
        BREADY => m_axi_data_port_BREADY,
        BRESP => m_axi_data_port_BRESP,
        BID => m_axi_data_port_BID,
        BUSER => m_axi_data_port_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => ap_const_logic_0,
        I_ARREADY => data_port_ARREADY,
        I_ARADDR => ap_const_lv32_0,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => ap_const_lv32_0,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => data_port_RVALID,
        I_RREADY => ap_const_logic_0,
        I_RDATA => data_port_RDATA,
        I_RID => data_port_RID,
        I_RUSER => data_port_RUSER,
        I_RRESP => data_port_RRESP,
        I_RLAST => data_port_RLAST,
        I_AWVALID => data_port_AWVALID,
        I_AWREADY => data_port_AWREADY,
        I_AWADDR => data_port_AWADDR,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => zext_ln552_reg_431,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => data_port_WVALID,
        I_WREADY => data_port_WREADY,
        I_WDATA => out_mem_V_load_reg_478,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv16_FFFF,
        I_BVALID => data_port_BVALID,
        I_BREADY => data_port_BREADY,
        I_BRESP => data_port_BRESP,
        I_BID => data_port_BID,
        I_BUSER => data_port_BUSER);

    regslice_both_store_queue_V_V_U : component regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => store_queue_V_V_TDATA,
        vld_in => store_queue_V_V_TVALID,
        ack_in => regslice_both_store_queue_V_V_U_ack_in,
        data_out => store_queue_V_V_TDATA_int,
        vld_out => store_queue_V_V_TVALID_int,
        ack_out => store_queue_V_V_TREADY_int,
        apdone_blk => regslice_both_store_queue_V_V_U_apdone_blk);

    regslice_both_g2s_dep_queue_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => g2s_dep_queue_V_TDATA,
        vld_in => g2s_dep_queue_V_TVALID,
        ack_in => regslice_both_g2s_dep_queue_V_U_ack_in,
        data_out => g2s_dep_queue_V_TDATA_int,
        vld_out => g2s_dep_queue_V_TVALID_int,
        ack_out => g2s_dep_queue_V_TREADY_int,
        apdone_blk => regslice_both_g2s_dep_queue_V_U_apdone_blk);

    regslice_both_s2g_dep_queue_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv8_1,
        vld_in => s2g_dep_queue_V_TVALID_int,
        ack_in => s2g_dep_queue_V_TREADY_int,
        data_out => s2g_dep_queue_V_TDATA,
        vld_out => regslice_both_s2g_dep_queue_V_U_vld_out,
        ack_out => s2g_dep_queue_V_TREADY,
        apdone_blk => regslice_both_s2g_dep_queue_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((data_port_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state4);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((data_port_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    dram_idx_V_reg_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((data_port_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                dram_idx_V_reg_204 <= add_ln304_reg_488;
            elsif ((not(((store_queue_V_V_TVALID_int = ap_const_logic_0) or (ap_start = ap_const_logic_0) or ((g2s_dep_queue_V_TVALID_int = ap_const_logic_0) and (tmp_6_fu_280_p3 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                dram_idx_V_reg_204 <= store_queue_V_V_TDATA_int(57 downto 26);
            end if; 
        end if;
    end process;

    phi_ln552_reg_225_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln552_fu_357_p2 = ap_const_lv1_0))) then 
                phi_ln552_reg_225 <= add_ln552_fu_362_p2;
            elsif (((data_port_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                phi_ln552_reg_225 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    sram_idx_V_0_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((data_port_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                sram_idx_V_0_reg_194 <= sram_idx_V_1_reg_483;
            elsif ((not(((store_queue_V_V_TVALID_int = ap_const_logic_0) or (ap_start = ap_const_logic_0) or ((g2s_dep_queue_V_TVALID_int = ap_const_logic_0) and (tmp_6_fu_280_p3 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                sram_idx_V_0_reg_194 <= store_queue_V_V_TDATA_int(25 downto 10);
            end if; 
        end if;
    end process;

    y_0_reg_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((data_port_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                y_0_reg_214 <= y_reg_439;
            elsif ((not(((store_queue_V_V_TVALID_int = ap_const_logic_0) or (ap_start = ap_const_logic_0) or ((g2s_dep_queue_V_TVALID_int = ap_const_logic_0) and (tmp_6_fu_280_p3 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_0_reg_214 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln304_reg_488 <= add_ln304_fu_387_p2;
                sram_idx_V_1_reg_483 <= sram_idx_V_1_fu_382_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln547_fu_316_p2 = ap_const_lv1_0))) then
                add_ln551_reg_444 <= add_ln551_fu_331_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln552_reg_464 <= icmp_ln552_fu_357_p2;
                icmp_ln552_reg_464_pp0_iter1_reg <= icmp_ln552_reg_464;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln552_reg_464 = ap_const_lv1_0))) then
                out_mem_V_load_reg_478 <= out_mem_V_Dout_A;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((store_queue_V_V_TVALID_int = ap_const_logic_0) or (ap_start = ap_const_logic_0) or ((g2s_dep_queue_V_TVALID_int = ap_const_logic_0) and (tmp_6_fu_280_p3 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    p_cast_reg_392(27 downto 0) <= p_cast_fu_246_p1(27 downto 0);
                tmp_1_reg_407 <= store_queue_V_V_TDATA_int(95 downto 80);
                tmp_V_reg_397 <= store_queue_V_V_TDATA_int;
                tmp_reg_402 <= store_queue_V_V_TDATA_int(79 downto 64);
                    zext_ln304_reg_426(15 downto 0) <= zext_ln304_fu_308_p1(15 downto 0);
                    zext_ln552_reg_431(15 downto 0) <= zext_ln552_fu_312_p1(15 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln547_fu_316_p2 = ap_const_lv1_1))) then
                tmp_7_reg_449 <= tmp_V_reg_397(5 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((data_port_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                trunc_ln552_reg_459 <= trunc_ln552_fu_353_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                y_reg_439 <= y_fu_321_p2;
            end if;
        end if;
    end process;
    p_cast_reg_392(32 downto 28) <= "00000";
    zext_ln304_reg_426(31 downto 16) <= "0000000000000000";
    zext_ln552_reg_431(31 downto 16) <= "0000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_enable_reg_pp0_iter2, ap_CS_fsm_state11, tmp_6_fu_280_p3, ap_CS_fsm_state2, icmp_ln547_fu_316_p2, ap_CS_fsm_state12, data_port_AWREADY, data_port_BVALID, ap_block_state2_io, icmp_ln552_fu_357_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, regslice_both_s2g_dep_queue_V_U_apdone_blk, ap_block_state12_io, store_queue_V_V_TVALID_int, g2s_dep_queue_V_TVALID_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((store_queue_V_V_TVALID_int = ap_const_logic_0) or (ap_start = ap_const_logic_0) or ((g2s_dep_queue_V_TVALID_int = ap_const_logic_0) and (tmp_6_fu_280_p3 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln547_fu_316_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                elsif (((ap_const_boolean_0 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln547_fu_316_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((data_port_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln552_fu_357_p2 = ap_const_lv1_1))) and not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln552_fu_357_p2 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((data_port_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if ((not(((ap_const_boolean_1 = ap_block_state12_io) or (regslice_both_s2g_dep_queue_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    add_ln304_fu_387_p2 <= std_logic_vector(unsigned(dram_idx_V_reg_204) + unsigned(zext_ln304_reg_426));
    add_ln551_fu_331_p2 <= std_logic_vector(unsigned(p_cast_reg_392) + unsigned(zext_ln215_fu_327_p1));
    add_ln552_1_fu_372_p2 <= std_logic_vector(unsigned(trunc_ln552_1_fu_368_p1) + unsigned(trunc_ln552_reg_459));
    add_ln552_fu_362_p2 <= std_logic_vector(unsigned(phi_ln552_reg_225) + unsigned(ap_const_lv16_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(8);
    ap_CS_fsm_state12 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state7 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_const_boolean_1 = ap_block_state6_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_boolean_1 = ap_block_state6_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_state1_assign_proc : process(ap_start, tmp_6_fu_280_p3, store_queue_V_V_TVALID_int, g2s_dep_queue_V_TVALID_int)
    begin
                ap_block_state1 <= ((store_queue_V_V_TVALID_int = ap_const_logic_0) or (ap_start = ap_const_logic_0) or ((g2s_dep_queue_V_TVALID_int = ap_const_logic_0) and (tmp_6_fu_280_p3 = ap_const_lv1_1)));
    end process;


    ap_block_state12_io_assign_proc : process(tmp_7_reg_449, s2g_dep_queue_V_TREADY_int)
    begin
                ap_block_state12_io <= ((s2g_dep_queue_V_TREADY_int = ap_const_logic_0) and (tmp_7_reg_449 = ap_const_lv1_1));
    end process;


    ap_block_state2_io_assign_proc : process(ap_predicate_op53_write_state2, s2g_dep_queue_V_TREADY_int)
    begin
                ap_block_state2_io <= ((s2g_dep_queue_V_TREADY_int = ap_const_logic_0) and (ap_predicate_op53_write_state2 = ap_const_boolean_1));
    end process;

        ap_block_state4_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_io_assign_proc : process(icmp_ln552_reg_464_pp0_iter1_reg, data_port_WREADY)
    begin
                ap_block_state6_io <= ((data_port_WREADY = ap_const_logic_0) and (icmp_ln552_reg_464_pp0_iter1_reg = ap_const_lv1_0));
    end process;

        ap_block_state6_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state4_assign_proc : process(icmp_ln552_fu_357_p2)
    begin
        if ((icmp_ln552_fu_357_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state12, regslice_both_s2g_dep_queue_V_U_apdone_blk, ap_block_state12_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state12_io) or (regslice_both_s2g_dep_queue_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op53_write_state2_assign_proc : process(icmp_ln547_fu_316_p2, tmp_7_fu_336_p3)
    begin
                ap_predicate_op53_write_state2 <= ((tmp_7_fu_336_p3 = ap_const_lv1_1) and (icmp_ln547_fu_316_p2 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state12, regslice_both_s2g_dep_queue_V_U_apdone_blk, ap_block_state12_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state12_io) or (regslice_both_s2g_dep_queue_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    data_port_AWADDR <= zext_ln551_fu_343_p1(32 - 1 downto 0);

    data_port_AWVALID_assign_proc : process(ap_CS_fsm_state3, data_port_AWREADY)
    begin
        if (((data_port_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_port_AWVALID <= ap_const_logic_1;
        else 
            data_port_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    data_port_BREADY_assign_proc : process(ap_CS_fsm_state11, data_port_BVALID)
    begin
        if (((data_port_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            data_port_BREADY <= ap_const_logic_1;
        else 
            data_port_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    data_port_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln552_reg_464_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln552_reg_464_pp0_iter1_reg = ap_const_lv1_0))) then 
            data_port_WVALID <= ap_const_logic_1;
        else 
            data_port_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    data_port_blk_n_AW_assign_proc : process(m_axi_data_port_AWREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_port_blk_n_AW <= m_axi_data_port_AWREADY;
        else 
            data_port_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    data_port_blk_n_B_assign_proc : process(m_axi_data_port_BVALID, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            data_port_blk_n_B <= m_axi_data_port_BVALID;
        else 
            data_port_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    data_port_blk_n_W_assign_proc : process(m_axi_data_port_WREADY, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln552_reg_464_pp0_iter1_reg)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln552_reg_464_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_port_blk_n_W <= m_axi_data_port_WREADY;
        else 
            data_port_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    g2s_dep_queue_V_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_6_fu_280_p3, g2s_dep_queue_V_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_6_fu_280_p3 = ap_const_lv1_1))) then 
            g2s_dep_queue_V_TDATA_blk_n <= g2s_dep_queue_V_TVALID_int;
        else 
            g2s_dep_queue_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    g2s_dep_queue_V_TREADY_assign_proc : process(g2s_dep_queue_V_TVALID, regslice_both_g2s_dep_queue_V_U_ack_in)
    begin
        if (((g2s_dep_queue_V_TVALID = ap_const_logic_1) and (regslice_both_g2s_dep_queue_V_U_ack_in = ap_const_logic_1))) then 
            g2s_dep_queue_V_TREADY <= ap_const_logic_1;
        else 
            g2s_dep_queue_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    g2s_dep_queue_V_TREADY_int_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_6_fu_280_p3, store_queue_V_V_TVALID_int, g2s_dep_queue_V_TVALID_int)
    begin
        if ((not(((store_queue_V_V_TVALID_int = ap_const_logic_0) or (ap_start = ap_const_logic_0) or ((g2s_dep_queue_V_TVALID_int = ap_const_logic_0) and (tmp_6_fu_280_p3 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_6_fu_280_p3 = ap_const_lv1_1))) then 
            g2s_dep_queue_V_TREADY_int <= ap_const_logic_1;
        else 
            g2s_dep_queue_V_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln547_fu_316_p2 <= "1" when (y_0_reg_214 = tmp_reg_402) else "0";
    icmp_ln552_fu_357_p2 <= "1" when (phi_ln552_reg_225 = tmp_1_reg_407) else "0";
    out_mem_V_Addr_A <= std_logic_vector(shift_left(unsigned(out_mem_V_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    out_mem_V_Addr_A_orig <= zext_ln552_1_fu_377_p1(32 - 1 downto 0);
    out_mem_V_Clk_A <= ap_clk;
    out_mem_V_Din_A <= ap_const_lv128_lc_1;

    out_mem_V_EN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_mem_V_EN_A <= ap_const_logic_1;
        else 
            out_mem_V_EN_A <= ap_const_logic_0;
        end if; 
    end process;


    out_mem_V_Rst_A_assign_proc : process(ap_rst_n)
    begin
                out_mem_V_Rst_A <= not(ap_rst_n);
    end process;

    out_mem_V_WEN_A <= ap_const_lv16_0;
    p_cast_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_236_p4),33));

    s2g_dep_queue_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, icmp_ln547_fu_316_p2, tmp_7_fu_336_p3, ap_CS_fsm_state12, tmp_7_reg_449, s2g_dep_queue_V_TREADY_int)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_7_reg_449 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_7_fu_336_p3 = ap_const_lv1_1) and (icmp_ln547_fu_316_p2 = ap_const_lv1_1)))) then 
            s2g_dep_queue_V_TDATA_blk_n <= s2g_dep_queue_V_TREADY_int;
        else 
            s2g_dep_queue_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s2g_dep_queue_V_TVALID <= regslice_both_s2g_dep_queue_V_U_vld_out;

    s2g_dep_queue_V_TVALID_int_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op53_write_state2, ap_block_state2_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_io) and (ap_predicate_op53_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            s2g_dep_queue_V_TVALID_int <= ap_const_logic_1;
        else 
            s2g_dep_queue_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    sram_idx_V_1_fu_382_p2 <= std_logic_vector(unsigned(tmp_1_reg_407) + unsigned(sram_idx_V_0_reg_194));

    store_queue_V_V_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, store_queue_V_V_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            store_queue_V_V_TDATA_blk_n <= store_queue_V_V_TVALID_int;
        else 
            store_queue_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    store_queue_V_V_TREADY_assign_proc : process(store_queue_V_V_TVALID, regslice_both_store_queue_V_V_U_ack_in)
    begin
        if (((store_queue_V_V_TVALID = ap_const_logic_1) and (regslice_both_store_queue_V_V_U_ack_in = ap_const_logic_1))) then 
            store_queue_V_V_TREADY <= ap_const_logic_1;
        else 
            store_queue_V_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    store_queue_V_V_TREADY_int_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_6_fu_280_p3, store_queue_V_V_TVALID_int, g2s_dep_queue_V_TVALID_int)
    begin
        if ((not(((store_queue_V_V_TVALID_int = ap_const_logic_0) or (ap_start = ap_const_logic_0) or ((g2s_dep_queue_V_TVALID_int = ap_const_logic_0) and (tmp_6_fu_280_p3 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            store_queue_V_V_TREADY_int <= ap_const_logic_1;
        else 
            store_queue_V_V_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_260_p4 <= store_queue_V_V_TDATA_int(95 downto 80);
    tmp_2_fu_236_p4 <= outputs_V(31 downto 4);
    tmp_3_fu_270_p4 <= store_queue_V_V_TDATA_int(111 downto 96);
    tmp_6_fu_280_p3 <= store_queue_V_V_TDATA_int(3 downto 3);
    tmp_7_fu_336_p3 <= tmp_V_reg_397(5 downto 5);
    trunc_ln552_1_fu_368_p1 <= phi_ln552_reg_225(13 - 1 downto 0);
    trunc_ln552_fu_353_p1 <= sram_idx_V_0_reg_194(13 - 1 downto 0);
    y_fu_321_p2 <= std_logic_vector(unsigned(y_0_reg_214) + unsigned(ap_const_lv16_1));
    zext_ln215_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dram_idx_V_reg_204),33));
    zext_ln304_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_270_p4),32));
    zext_ln551_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln551_reg_444),64));
    zext_ln552_1_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln552_1_fu_372_p2),64));
    zext_ln552_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_260_p4),32));
end behav;
